# -*- python -*-
import os
import lsst.utils
from lsst.sconsUtils import scripts, env

try:
    afwdataDir = lsst.utils.getPackageDir('afwdata')
except Exception:
    print "Warning: afwdata is not set up; not running the tests!"
else:
    # copy AFWDATA_DIR to the test's environment
    env["ENV"]["AFWDATA_DIR"] = afwdataDir
    scripts.BasicSConscript.tests()
