# -*- python -*-
import os
from lsst.sconsUtils import scripts, env

dataDir = env.ProductDir("afwdata")
if not dataDir:
    print "Warning: afwdata is not set up; not running the tests!"
else:    
    # copy AFWDATA_DIR to the test's environment
    env["ENV"]["AFWDATA_DIR"] = os.environ["AFWDATA_DIR"]

    scripts.BasicSConscript.tests(args=testArgs)
