# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.python(["_coaddUtilsLib"], [
    '_coaddUtilsLib.cc',
    'addToCoadd.cc',
    'copyGoodPixels.cc',
    'setCoaddEdgeBits.cc'
])
