# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['addToCoadd',
                                  'copyGoodPixels',
                                  'setCoaddEdgeBits'], addUnderscore=False)
